### ISSUE TITLE
2.4. Длина комментария не может составлять больше 140 символов;

### ISSUE THREAD

**Issue by baileys-li** [htmlacademy/js1-kekstagram-e2e#1]
Текущий тест на переполнение завязан на ожидание ошибки Pristine в DOM, хотя в Техническом задании нет чёткой оговерености про такое поведение.
![image](https://github.com/htmlacademy/js1-kekstagram-e2e/assets/47776594/4a35dc14-175d-4c22-b2da-e486c637d922)

Если задать `<textarea>` атрибут `maxlength` то из сообщения:
> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel eros nulla. Etiam nec sodales leo. Ut facilisis orci non dolor dapibus nec.

Обрежется точка и отправка формы будет выполнена.

Вариант с использованием нативного `maxlength` должен считаться валидным, поскольку его обозначили валидным:
* @sashasushko в [9.5. Видеоразбор. Учебный проект: валидация формы ](https://up.htmlacademy.ru/javascript/29/module/9/item/5)
* @Jahonta в [9.16. Лайв «Ретроспектива. Внешние API и сторонние библиотеки»](https://up.htmlacademy.ru/javascript/29/module/9/item/16) (хоть там дана преференция на Pristine)

Я считаю выбор Pristine антипаттерном, потому что нет необходимости изобретать велосипед, когда браузер и так делает это лучше. Кроме того, сама библиотека Pristine вызывает негативные эмоции

**Comment by sashasushko** [comment]
Вот это привет из прошлого 😄

**Comment by Jahonta** [comment]
Спасибо за ишью. Я тоже видела, как студенты страдали от этого кейса.

Уточним в новом потоке техническое задание. Для UX лучше всё-таки показывать внятную ошибку, поэтому добавим чёткое требование её выводить при превышении длины.
Выбрали такой подход, потому что это курс про JS и хочется, чтобы студенты потренировались управлять формой именно с помощью скрипта. Ну и в следующих курсах им также придётся валидировать пользовательский ввод самим, не полагаясь на браузер.
