### ISSUE TITLE
3.3. При успешной отправке формы форма редактирования изображения закрывается

### ISSUE THREAD

**Issue by baileys-li** [htmlacademy/js1-kekstagram-e2e#2]
Вот это явная бага. Тест ждёт, что на `body` нет класса `modal-open`. Но на этом шаге ещё открыта модалка, и как раз этот класс ожидаем. Похоже, тест просто заточен под какую-то неправильную реализацию.
![Ссылка на изображение](https://github.com/htmlacademy/js1-kekstagram-e2e/assets/47776594/ec4826cb-5cba-4fba-a440-10f5b49d143c)
Также очень плохо, что тесты вообще захардкожены на какие-то классы. Это не бизнес-логика.

**Comment by Jahonta** [comment]
Привет!
Класс `modal-open` добавляется, если открыта модалка с полноразмерным изображением или форма добавления изображения. Требования добавлять этот класс при показе информационного сообщения нет. Более того, явно сказано, что когда форма закрывается, этот класс нужно убрать.
Поэтому в данном случае тесты соответствуют техническому заданию.

**Comment by baileys-li** [comment]
Да, но при это тоже модальное окно и когда поведение отличается это неприятно
