### ISSUE TITLE
4.4. При нажатии на любую из миниатюр, показывается блок `.big-picture`

### ISSUE THREAD

**Issue by baileys-li** [htmlacademy/js1-kekstagram-e2e#3]
_Повтор [ишью](https://github.com/htmlacademy/yomoyo/issues/1116) от @sineway. 
Просто чтобы все они были в одном месте и можно было удобно закрывать позже через ПР._

![Ссылка на изображение](https://github.com/htmlacademy/js1-kekstagram-e2e/assets/47776594/eb6fb48b-6b12-46a1-b382-cc487de52ba4)
#### Почему текущие тесты не подходят:
- Они завязаны на проверку определенных классов, что означает привязку к определенной технической реализации, а не к бизнес-логике.
- В реальном проекте могут вполне перерендеривать всю строку _«5 из 9 комментариев»_, поскольку:
  - На элементах счётчиков нет никаких стилей и ролей.
  - По производительности это будет одинаково.
  - Разработчик может захотеть использовать правила для множественного числа (plural rules), чтобы было _«1 из 1 комментария»_. На прошлых потоках, когда на `textarea` были ограничения минимальной длины, было более актуально, чтобы ещё считать, сколько символов осталось. Также в Кексобукинге это пригождалось.
  - В реальном проекте, особенно с интернализацией, скорее всего, из-за тех же правил для множественного числа, переписывали бы всю строку.

**Comment by Jahonta** [comment]
Привет!
Тесты на курсе проверяют не бизнес-логику, а соответствие техническому заданию, то есть критерий Б1. Если в ТЗ сказано, что должны использоваться такие-то классы, то тесты проверяют, в числе прочего, их правильное использование.
Для душевного спокойствия можно представить, что это не классы, а `testId`, которые тест ожидает увидеть на странице. Если не увидит, упадёт.

Что касается конкретной строчки, то в следующем потоке подправим разметку и будем проверять, что в указанных в ТЗ элементах содержатся правильные числа, а от проверки строки целиком откажемся. Это позволит студентам, если они захотят, изменять форму существительного.
Что касается переписывания всей строки, то никто не запрещает делать это и дальше, просто не перезатирая разметку (с помощью `innerHTML` и внимательного отношения к вставляемым данным).
Сейчас стилей и другой логики на этих элементах нет, но в будущем они могут появиться. И что, если верстальщик добавит пару строчек CSS, разработчику придётся переписывать логику?
Да и в принципе это хороший учебный кейс: на этом примере можно показать студентам, как точечно вставлять динамически изменяющиеся данные на страницу, какие подходы есть, что следует учитывать и так далее.
